name: Generate Datas

on:
  schedule:
    - cron: '0 */12 * * *'  # This will run the workflow every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Make sure to checkout the code

      # Snake Animation
      - uses: Platane/snk@v3  # Use a specific stable version
        with:
          github_user_name: BILYYY
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
